### ISSUE TITLE
cordova platform add android

### ISSUE THREAD

**Issue by jalle007** [zyra/ionic-super-tabs#407]
cordova.cmd platform add android
{ Error: npm: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\xxx\AppData\Roaming\nvm\v10.15.3\node_modules\cordova\node_modules\cordova-common\src\superspawn.js:135:23)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.cp.emit (C:\Users\xxx\AppData\Roaming\nvm\v10.15.3\node_modules\cordova\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12) code: 1 }

**Comment by ihadeed** [comment]
I can't see how this is related.
